# Generated by Django 4.0.4 on 2022-05-17 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bankaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30)),
                ('IFC_code', models.CharField(max_length=30)),
                ('Bank_name', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobilenumber', models.CharField(max_length=30)),
                ('idproof', models.CharField(choices=[('Aadhaar Card', 'Aadhaar Card'), ('Passport', 'Passport'), ('Driving Licence', 'Driving Licence'), ('Voter ID', 'Voter ID'), ('Pan Card', 'Pan Card')], max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Creditcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MMID', models.CharField(max_length=30)),
                ('mobilenumber', models.CharField(max_length=30)),
                ('credit_card_number', models.CharField(max_length=30)),
                ('amount', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Debitcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_card_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('amount', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Eclecticfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choices', models.CharField(choices=[('South Indian', 'South Indian'), ('North Indian', 'North Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Pan Asian', 'Pan Asian'), ('European', 'European'), ('Japanese', 'Japanese'), ('Casual Electic', 'Casual Electic'), ('Meditterranean', 'Meditterranean')], max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('mobilenumber', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payouts', models.CharField(choices=[('Bank Account', 'Bank Account'), ('Google pay', 'Google pay'), ('Paytm', 'Paytm'), ('Phonepe', 'Phonepe'), ('Paypal', 'Paypal'), ('Credit Card', 'Credit_Card'), ('Credit Card', 'Credit Card'), ('Cash', 'Cash')], max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('mobilenumber', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('amount', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aminities', models.CharField(choices=[('Single bedroom', 'Single bedroom'), ('Double bedroom', 'Double bedroom'), ('VIP bedroom', 'VIP bedroom'), ('Car parking', 'Car parking'), ('Eclectic food', 'Eclectic food'), ('Room services', 'Room services')], max_length=30)),
                ('amount', models.IntegerField(default=6000)),
            ],
        ),
        migrations.CreateModel(
            name='VIPbedroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('amount', models.TextField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Singlebedroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('amount', models.TextField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Roomservices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favors', models.CharField(choices=[('Centralized', 'Centralized'), ('Decentralized', 'Decentralized')], max_length=30)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.client')),
            ],
        ),
        migrations.CreateModel(
            name='Phonepe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPI_id', models.CharField(max_length=30)),
                ('paydetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.payments')),
            ],
        ),
        migrations.CreateModel(
            name='Paytm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPI_id', models.CharField(max_length=30)),
                ('paydetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.payments')),
            ],
        ),
        migrations.CreateModel(
            name='Paypal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('paydetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.payments')),
            ],
        ),
        migrations.CreateModel(
            name='Googlepay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UPI_id', models.CharField(max_length=30)),
                ('paydetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.payments')),
            ],
        ),
        migrations.CreateModel(
            name='Doublebedroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('amount', models.TextField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='services',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.services'),
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paydetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.payments')),
            ],
        ),
        migrations.CreateModel(
            name='Carparking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=30)),
                ('amount', models.TextField()),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resortapp.client')),
            ],
        ),
    ]
