# Generated by Django 4.0.4 on 2022-05-17 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='aminities',
            new_name='services',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='cash',
            name='paydetails',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='debitcard',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='googlepay',
            name='paydetails',
        ),
        migrations.RemoveField(
            model_name='paypal',
            name='paydetails',
        ),
        migrations.RemoveField(
            model_name='paytm',
            name='paydetails',
        ),
        migrations.RemoveField(
            model_name='phonepe',
            name='paydetails',
        ),
        migrations.AddField(
            model_name='payments',
            name='bankaccount',
            field=models.ForeignKey(default=25000, on_delete=django.db.models.deletion.CASCADE, to='resortapp.bankaccount'),
        ),
        migrations.AddField(
            model_name='payments',
            name='cash',
            field=models.ForeignKey(default=25000, on_delete=django.db.models.deletion.CASCADE, to='resortapp.cash'),
        ),
        migrations.AddField(
            model_name='payments',
            name='creditcard',
            field=models.ForeignKey(default=25000, on_delete=django.db.models.deletion.CASCADE, to='resortapp.creditcard'),
        ),
        migrations.AddField(
            model_name='payments',
            name='debitcard',
            field=models.ForeignKey(default=25000, on_delete=django.db.models.deletion.CASCADE, to='resortapp.debitcard'),
        ),
        migrations.AddField(
            model_name='payments',
            name='gpay',
            field=models.ForeignKey(default=25000, on_delete=django.db.models.deletion.CASCADE, to='resortapp.googlepay'),
        ),
        migrations.AddField(
            model_name='payments',
            name='paypal',
            field=models.ForeignKey(default=25000, on_delete=django.db.models.deletion.CASCADE, to='resortapp.paypal'),
        ),
        migrations.AddField(
            model_name='payments',
            name='paytm',
            field=models.ForeignKey(default=25000, on_delete=django.db.models.deletion.CASCADE, to='resortapp.paytm'),
        ),
        migrations.AddField(
            model_name='payments',
            name='phonepay',
            field=models.ForeignKey(default=25000, on_delete=django.db.models.deletion.CASCADE, to='resortapp.phonepe'),
        ),
        migrations.AlterField(
            model_name='carparking',
            name='amount',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='doublebedroom',
            name='amount',
            field=models.IntegerField(default=8000),
        ),
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.IntegerField(default=25000),
        ),
        migrations.AlterField(
            model_name='singlebedroom',
            name='amount',
            field=models.IntegerField(default=6000),
        ),
        migrations.AlterField(
            model_name='vipbedroom',
            name='amount',
            field=models.IntegerField(default=10000),
        ),
    ]
