# Generated by Django 4.0.4 on 2022-05-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0002_rename_aminities_services_services_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='services',
            name='amount',
        ),
    ]
