# Generated by Django 4.0.4 on 2022-05-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0004_remove_singlebedroom_details_eclecticfood_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='amount',
            field=models.IntegerField(default=25000),
        ),
    ]
