# Generated by Django 4.0.4 on 2022-05-18 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0005_bankaccount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='services',
        ),
    ]
