# Generated by Django 4.0.4 on 2022-05-18 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0006_remove_client_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='bankaccount',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='cash',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='creditcard',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='debitcard',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='gpay',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='paypal',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='paytm',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='phonepay',
        ),
        migrations.AddField(
            model_name='cash',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resortapp.payments'),
        ),
        migrations.AddField(
            model_name='googlepay',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resortapp.payments'),
        ),
        migrations.AddField(
            model_name='paypal',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resortapp.payments'),
        ),
        migrations.AddField(
            model_name='paytm',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resortapp.payments'),
        ),
        migrations.AddField(
            model_name='phonepe',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resortapp.payments'),
        ),
    ]
