# Generated by Django 4.0.4 on 2022-05-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0007_remove_bankaccount_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='carparking',
        ),
        migrations.RemoveField(
            model_name='services',
            name='doublebedroom',
        ),
        migrations.RemoveField(
            model_name='services',
            name='eclecticfood',
        ),
        migrations.RemoveField(
            model_name='services',
            name='roomservices',
        ),
        migrations.RemoveField(
            model_name='services',
            name='singlebedroom',
        ),
        migrations.RemoveField(
            model_name='services',
            name='vipbedroom',
        ),
    ]
