# Generated by Django 4.0.4 on 2022-05-18 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0008_remove_services_carparking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carparking',
            name='details',
        ),
        migrations.RemoveField(
            model_name='doublebedroom',
            name='details',
        ),
        migrations.RemoveField(
            model_name='eclecticfood',
            name='mobilenumber',
        ),
        migrations.RemoveField(
            model_name='eclecticfood',
            name='name',
        ),
        migrations.RemoveField(
            model_name='roomservices',
            name='details',
        ),
        migrations.RemoveField(
            model_name='singlebedroom',
            name='address',
        ),
        migrations.RemoveField(
            model_name='singlebedroom',
            name='idproof',
        ),
        migrations.RemoveField(
            model_name='singlebedroom',
            name='mobilenumber',
        ),
        migrations.RemoveField(
            model_name='singlebedroom',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vipbedroom',
            name='details',
        ),
        migrations.AddField(
            model_name='carparking',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resortapp.services'),
        ),
        migrations.AddField(
            model_name='doublebedroom',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resortapp.services'),
        ),
        migrations.AddField(
            model_name='eclecticfood',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resortapp.services'),
        ),
        migrations.AddField(
            model_name='roomservices',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resortapp.services'),
        ),
        migrations.AddField(
            model_name='services',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resortapp.client'),
        ),
        migrations.AddField(
            model_name='singlebedroom',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resortapp.services'),
        ),
        migrations.AddField(
            model_name='vipbedroom',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resortapp.services'),
        ),
    ]
