# Generated by Django 4.0.4 on 2022-05-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0009_remove_carparking_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='client',
        ),
        migrations.AddField(
            model_name='services',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='idproof',
            field=models.CharField(choices=[('Aadhaar Card', 'Aadhaar Card'), ('Passport', 'Passport'), ('Driving Licence', 'Driving Licence'), ('Voter ID', 'Voter ID'), ('Pan Card', 'Pan Card')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='mobilenumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
