# Generated by Django 4.0.4 on 2022-05-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0011_alter_services_idproof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='idproof',
            field=models.CharField(choices=[('Aadhaar Card', 'Aadhaar Card'), ('Passport', 'Passport'), ('Driving Licence', 'Driving Licence'), ('Voter ID', 'Voter ID'), ('Pan Card', 'Pan Card')], max_length=30, null=True),
        ),
    ]
