# Generated by Django 4.0.4 on 2022-05-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0012_alter_services_idproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
