# Generated by Django 4.0.4 on 2022-05-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0014_services_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='proof',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='proof',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
