# Generated by Django 4.0.4 on 2022-05-18 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0015_client_proof_services_proof'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Payments',
            new_name='Payment',
        ),
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
