# Generated by Django 4.0.4 on 2022-05-18 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0016_rename_payments_payment_rename_services_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 18, 0, 0)),
        ),
    ]
