# Generated by Django 4.0.4 on 2022-05-20 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0017_alter_service_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 0, 0)),
        ),
    ]
