# Generated by Django 4.0.4 on 2022-05-20 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0018_alter_service_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='datetime',
        ),
        migrations.AddField(
            model_name='service',
            name='serdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 13, 18, 48, 472614)),
        ),
    ]
