# Generated by Django 4.0.4 on 2022-05-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0019_remove_service_datetime_service_serdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='serdate',
        ),
        migrations.AlterField(
            model_name='service',
            name='mobilenumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
