# Generated by Django 2.0.1 on 2022-05-26 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0021_remove_payment_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='Bank_name',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='IFC_code',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='MMID',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='creditcard',
            name='mobilenumber',
        ),
        migrations.RemoveField(
            model_name='debitcard',
            name='address',
        ),
        migrations.RemoveField(
            model_name='debitcard',
            name='debit_card_number',
        ),
        migrations.RemoveField(
            model_name='googlepay',
            name='UPI_id',
        ),
        migrations.RemoveField(
            model_name='paypal',
            name='email',
        ),
        migrations.RemoveField(
            model_name='paytm',
            name='UPI_id',
        ),
        migrations.RemoveField(
            model_name='phonepe',
            name='UPI_id',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resortapp.Payment'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resortapp.Payment'),
        ),
        migrations.AddField(
            model_name='debitcard',
            name='payments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resortapp.Payment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='Bank_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='IFC_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='MMID',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='UPI_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='account_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='credit_card_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='debit_card_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='car_number',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='choices',
            field=models.CharField(choices=[('South Indian', 'South Indian'), ('North Indian', 'North Indian'), ('Chinese', 'Chinese'), ('Italian', 'Italian'), ('Pan Asian', 'Pan Asian'), ('European', 'European'), ('Japanese', 'Japanese'), ('Casual Electic', 'Casual Electic'), ('Meditterranean', 'Meditterranean')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='service',
            name='favors',
            field=models.CharField(choices=[('Centralized', 'Centralized'), ('Decentralized', 'Decentralized')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carparking',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cash',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='debitcard',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='doublebedroom',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eclecticfood',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='googlepay',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='address',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mobilenumber',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payouts',
            field=models.CharField(choices=[('Bank Account', 'Bank Account'), ('Google pay', 'Google pay'), ('Paytm', 'Paytm'), ('Phonepe', 'Phonepe'), ('Paypal', 'Paypal'), ('Credit Card', 'Credit_Card'), ('Credit Card', 'Credit Card'), ('Cash', 'Cash')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paypal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='paytm',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='phonepe',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='roomservices',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='services',
            field=models.CharField(choices=[('Single bedroom', 'Single bedroom'), ('Double bedroom', 'Double bedroom'), ('VIP bedroom', 'VIP bedroom'), ('Car parking', 'Car parking'), ('Eclectic food', 'Eclectic food'), ('Room services', 'Room services')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='singlebedroom',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vipbedroom',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
