# Generated by Django 2.0.1 on 2022-05-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resortapp', '0022_auto_20220526_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='Bank_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='IFC_code',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='MMID',
        ),
    ]
